version: "3.7"

services:
  post-db:
    image: "postgres:12.2"
    container_name: "post-db"
    environment:
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=post
      - POSTGRES_DB=Houses
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default
        
networks:
  default:
    driver: bridge
    name: net-post
